import { Flashcard } from './flashcard';

export const FlashcardData: Flashcard[] = [
  // =========================================================================
  // History
  // =========================================================================
  {
    category: 'History',
    question: 'What is the capital of France?',
    options: ['London', 'Paris', 'Berlin', 'Madrid'],
    correctAnswerIndex: 1,
    points: 10,
    hint: "It's known as the city of lights.",
  },
  {
    category: 'History',
    question: 'Who was the first president of the United States?',
    options: [
      'George Washington',
      'John Adams',
      'Thomas Jefferson',
      'James Madison',
    ],
    correctAnswerIndex: 0,
    points: 20,
    hint: 'He is featured on the one-dollar bill.',
  },
  {
    category: 'History',
    question: 'What is the Magna Carta?',
    options: [
      'A peace treaty between England and France',
      'A document limiting the power of the English monarch',
      'A law code established by Charlemagne',
      'The constitution of the Roman Republic',
    ],
    correctAnswerIndex: 1,
    points: 30,
    hint: 'It was signed in 1215 and influenced modern democracies.',
  },
  {
    category: 'History',
    question: 'When did the Berlin Wall fall?',
    options: ['1987', '1988', '1989', '1990'],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'It marked the end of the Cold War.',
  },
  {
    category: 'History',
    question: 'Who was the first Emperor of China?',
    options: ['Liu Bang', 'Qin Shi Huang', 'Han Wudi', 'Emperor Gaozu'],
    correctAnswerIndex: 1,
    points: 30,
    hint: 'He is known for beginning construction on the Great Wall.',
  },
  {
    category: 'History',
    question: 'Who was the first female Prime Minister of the United Kingdom?',
    options: [
      'Margaret Thatcher',
      'Theresa May',
      'Angela Merkel',
      'Indira Gandhi',
    ],
    correctAnswerIndex: 0,
    points: 20,
    hint: "She was known as the 'Iron Lady.'",
  },
  {
    category: 'History',
    question: 'In which year did the Titanic sink?',
    options: ['1910', '1911', '1912', '1913'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'The tragic event happened on April 15th of this year.',
  },
  {
    category: 'History',
    question: 'Who wrote the Declaration of Independence?',
    options: [
      'Benjamin Franklin',
      'George Washington',
      'Thomas Jefferson',
      'John Adams',
    ],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'He was also the 3rd president of the United States.',
  },
  {
    category: 'History',
    question: 'What ancient civilization built the Machu Picchu?',
    options: ['Aztec', 'Inca', 'Maya', 'Olmec'],
    correctAnswerIndex: 1,
    points: 30,
    hint: 'This civilization lived in what is now Peru.',
  },
  {
    category: 'History',
    question: 'What was the primary cause of the Cold War?',
    options: [
      'Religious conflicts',
      'Territorial disputes',
      'Ideological differences',
      'Resource scarcity',
    ],
    correctAnswerIndex: 2,
    points: 30,
    hint: 'It was a rivalry between capitalism and communism.',
  },
  {
    category: 'History',
    question: 'Who was the second president of the United States?',
    options: [
      'Thomas Jefferson',
      'John Adams',
      'James Madison',
      'Alexander Hamilton',
    ],
    correctAnswerIndex: 1,
    points: 20,
    hint: "He served as George Washington's Vice President first.",
  },
  {
    category: 'History',
    question: 'In what year did World War II end?',
    options: ['1943', '1944', '1945', '1946'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'It ended the same year the United Nations was established.',
  },
  {
    category: 'History',
    question: 'Which empire built the Colosseum?',
    options: [
      'The Greek Empire',
      'The Roman Empire',
      'The Ottoman Empire',
      'The Byzantine Empire',
    ],
    correctAnswerIndex: 1,
    points: 10,
    hint: 'This empire was centered in what is modern-day Italy.',
  },
  {
    category: 'History',
    question:
      'Who was the famous queen of ancient Egypt known for her relationships with Julius Caesar and Mark Antony?',
    options: ['Nefertiti', 'Hatshepsut', 'Cleopatra', 'Sobekneferu'],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'She was the last active ruler of the Ptolemaic Kingdom of Egypt.',
  },
  {
    category: 'History',
    question:
      'What was the name of the ship that brought the Pilgrims to America in 1620?',
    options: ['Santa Maria', 'Mayflower', 'Discovery', 'Endeavour'],
    correctAnswerIndex: 1,
    points: 10,
    hint: 'It shares its name with a spring flower.',
  },
  {
    category: 'History',
    question: 'Who discovered America in 1492?',
    options: [
      'Vasco da Gama',
      'Ferdinand Magellan',
      'Christopher Columbus',
      'Leif Erikson',
    ],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'He sailed the ocean blue in fourteen hundred ninety-two.',
  },
  {
    category: 'History',
    question: 'The Renaissance began in which country?',
    options: ['France', 'Spain', 'England', 'Italy'],
    correctAnswerIndex: 3,
    points: 20,
    hint: 'It started in cities like Florence and Venice.',
  },
  {
    category: 'History',
    question: 'Who was assassinated to spark the beginning of World War I?',
    options: [
      'Archduke Franz Ferdinand',
      'Tsar Nicholas II',
      'Kaiser Wilhelm II',
      'Woodrow Wilson',
    ],
    correctAnswerIndex: 0,
    points: 30,
    hint: 'He was the heir presumptive to the Austro-Hungarian throne.',
  },
  {
    category: 'History',
    question: 'What is the name of the oldest written set of laws?',
    options: [
      'Ten Commandments',
      'Code of Hammurabi',
      'Magna Carta',
      'Justinian Code',
    ],
    correctAnswerIndex: 1,
    points: 30,
    hint: "It includes the phrase 'an eye for an eye'.",
  },
  {
    category: 'History',
    question: 'Which French leader was defeated at the Battle of Waterloo?',
    options: [
      'Louis XIV',
      'Robespierre',
      'Napoleon Bonaparte',
      'Charles de Gaulle',
    ],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'He crowned himself Emperor of the French in 1804.',
  },
  {
    category: 'History',
    question:
      "Who was the civil rights leader famous for his 'I Have a Dream' speech?",
    options: [
      'Malcolm X',
      'Martin Luther King Jr.',
      'Nelson Mandela',
      'Frederick Douglass',
    ],
    correctAnswerIndex: 1,
    points: 10,
    hint: 'The speech was delivered during the 1963 March on Washington.',
  },
  {
    category: 'History',
    question: 'The Soviet Union collapsed in what year?',
    options: ['1989', '1990', '1991', '1992'],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'It officially dissolved on December 26 of this year.',
  },
  {
    category: 'History',
    question:
      "Which historical figure was known as Alexander the Great's teacher?",
    options: ['Socrates', 'Plato', 'Aristotle', 'Pythagoras'],
    correctAnswerIndex: 2,
    points: 30,
    hint: 'He was a student of Plato.',
  },
  {
    category: 'History',
    question:
      'What was the name of the route that connected China to the Mediterranean Sea?',
    options: [
      'The Spice Route',
      'The Silk Road',
      'The Amber Road',
      'The Royal Road',
    ],
    correctAnswerIndex: 1,
    points: 20,
    hint: 'It is named after a luxurious fabric.',
  },
  {
    category: 'History',
    question: 'Who was the first woman to fly solo across the Atlantic Ocean?',
    options: [
      'Bessie Coleman',
      'Harriet Quimby',
      'Amelia Earhart',
      'Jacqueline Cochran',
    ],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'She mysteriously disappeared in 1937.',
  },
  {
    category: 'History',
    question: 'The French Revolution began with the storming of which prison?',
    options: [
      'The Tower of London',
      'The Bastille',
      'Alcatraz',
      "Château d'If",
    ],
    correctAnswerIndex: 1,
    points: 20,
    hint: 'It happened on July 14, 1789.',
  },
  {
    category: 'History',
    question:
      'Which war was fought between the northern and southern states of the US?',
    options: [
      'Revolutionary War',
      'War of 1812',
      'The Civil War',
      'The Spanish-American War',
    ],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'Abraham Lincoln was president during this conflict.',
  },
  {
    category: 'History',
    question: 'Who painted the ceiling of the Sistine Chapel?',
    options: ['Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Donatello'],
    correctAnswerIndex: 1,
    points: 20,
    hint: 'He was also the sculptor of David.',
  },
  {
    category: 'History',
    question:
      'What ancient city was destroyed by the eruption of Mount Vesuvius?',
    options: ['Rome', 'Athens', 'Pompeii', 'Sparta'],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'Its ruins were preserved under volcanic ash.',
  },
  {
    category: 'History',
    question: 'Nelson Mandela was the first black president of which country?',
    options: ['Kenya', 'Nigeria', 'South Africa', 'Zimbabwe'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'He spent 27 years in prison fighting against apartheid.',
  },

  // =========================================================================
  // Geography
  // =========================================================================
  {
    category: 'Geography',
    question: 'What is the largest ocean on Earth?',
    options: [
      'Atlantic Ocean',
      'Pacific Ocean',
      'Indian Ocean',
      'Arctic Ocean',
    ],
    correctAnswerIndex: 1,
    points: 10,
    hint: "It covers more than 30% of the Earth's surface.",
  },
  {
    category: 'Geography',
    question: 'What is the tallest mountain in the world?',
    options: ['Mount Everest', 'K2', 'Kangchenjunga', 'Lhotse'],
    correctAnswerIndex: 0,
    points: 20,
    hint: 'It stands at over 29,000 feet tall.',
  },
  {
    category: 'Geography',
    question:
      'What is the name of the desert that covers most of the Arabian Peninsula?',
    options: ['Sahara', 'Gobi', 'Atacama', 'Australian Outback'],
    correctAnswerIndex: 0,
    points: 30,
    hint: "It's the world's largest hot desert.",
  },
  {
    category: 'Geography',
    question: 'Which country has the longest coastline?',
    options: ['Canada', 'Russia', 'Australia', 'USA'],
    correctAnswerIndex: 0,
    points: 20,
    hint: 'This country is known for its large number of lakes.',
  },
  {
    category: 'Geography',
    question: 'What river runs through Baghdad?',
    options: ['Nile', 'Tigris', 'Euphrates', 'Jordan'],
    correctAnswerIndex: 1,
    points: 20,
    hint: 'It was one of the rivers in ancient Mesopotamia.',
  },
  {
    category: 'Geography',
    question: 'What is the smallest country in the world by land area?',
    options: ['Monaco', 'Nauru', 'Vatican City', 'San Marino'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'This country is located entirely within Rome.',
  },
  {
    category: 'Geography',
    question: 'Which continent is the Sahara Desert located on?',
    options: ['Asia', 'Africa', 'Australia', 'South America'],
    correctAnswerIndex: 1,
    points: 10,
    hint: 'This desert is located on the continent known for its wildlife.',
  },
  {
    category: 'Geography',
    question: 'Which country has the most natural lakes?',
    options: ['USA', 'Canada', 'Russia', 'Finland'],
    correctAnswerIndex: 1,
    points: 20,
    hint: "More than half of the world's lakes are in this country.",
  },
  {
    category: 'Geography',
    question: 'What is the longest river in the world?',
    options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'],
    correctAnswerIndex: 1,
    points: 20,
    hint: 'It runs through Egypt.',
  },
  {
    category: 'Geography',
    question: 'What is the capital of Australia?',
    options: ['Sydney', 'Melbourne', 'Brisbane', 'Canberra'],
    correctAnswerIndex: 3,
    points: 10,
    hint: "It's not the largest city but is the political center.",
  },
  {
    category: 'Geography',
    question: "Which continent is known as the 'Dark Continent'?",
    options: ['Asia', 'Africa', 'South America', 'Antarctica'],
    correctAnswerIndex: 1,
    points: 10,
    hint: 'This term was historically used by Europeans.',
  },
  {
    category: 'Geography',
    question: 'What is the capital of Japan?',
    options: ['Kyoto', 'Osaka', 'Tokyo', 'Seoul'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'It was formerly known as Edo.',
  },
  {
    category: 'Geography',
    question: 'Which river flows through Paris?',
    options: ['Thames', 'Rhine', 'Seine', 'Danube'],
    correctAnswerIndex: 2,
    points: 20,
    hint: "It's famous for its romantic boat cruises.",
  },
  {
    category: 'Geography',
    question: 'What is the largest country in the world by land area?',
    options: ['Canada', 'China', 'United States', 'Russia'],
    correctAnswerIndex: 3,
    points: 10,
    hint: 'It spans across both Eastern Europe and Northern Asia.',
  },
  {
    category: 'Geography',
    question: 'Mount Kilimanjaro is located in which country?',
    options: ['Kenya', 'Tanzania', 'South Africa', 'Uganda'],
    correctAnswerIndex: 1,
    points: 30,
    hint: "It's the highest single free-standing mountain in the world.",
  },
  {
    category: 'Geography',
    question: 'What is the capital of Canada?',
    options: ['Toronto', 'Vancouver', 'Montreal', 'Ottawa'],
    correctAnswerIndex: 3,
    points: 20,
    hint: 'It is located in the province of Ontario.',
  },
  {
    category: 'Geography',
    question: 'Which of these is not a continent?',
    options: ['Europe', 'Antarctica', 'Greenland', 'Australia'],
    correctAnswerIndex: 2,
    points: 10,
    hint: "It's the world's largest island.",
  },
  {
    category: 'Geography',
    question: 'The Great Barrier Reef is off the coast of which country?',
    options: ['Brazil', 'Australia', 'Indonesia', 'Philippines'],
    correctAnswerIndex: 1,
    points: 10,
    hint: 'It is located in the Coral Sea.',
  },
  {
    category: 'Geography',
    question: 'What is the capital of Brazil?',
    options: ['Rio de Janeiro', 'São Paulo', 'Brasília', 'Salvador'],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'It was planned and built specifically to be the new capital in 1960.',
  },
  {
    category: 'Geography',
    question:
      'The Alps mountain range does NOT pass through which of these countries?',
    options: ['Switzerland', 'Italy', 'Austria', 'Spain'],
    correctAnswerIndex: 3,
    points: 30,
    hint: 'This country has the Pyrenees instead.',
  },
  {
    category: 'Geography',
    question: 'What is the longest river in Europe?',
    options: ['Danube', 'Volga', 'Rhine', 'Ural'],
    correctAnswerIndex: 1,
    points: 30,
    hint: 'It flows through Central Russia.',
  },
  {
    category: 'Geography',
    question: 'Which U.S. state has the most active volcanoes?',
    options: ['California', 'Washington', 'Alaska', 'Hawaii'],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'It is the largest U.S. state by area.',
  },
  {
    category: 'Geography',
    question: 'What is the capital of Egypt?',
    options: ['Alexandria', 'Giza', 'Cairo', 'Luxor'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'It is located near the Nile Delta.',
  },
  {
    category: 'Geography',
    question: 'In which ocean is the Bermuda Triangle located?',
    options: ['Pacific', 'Atlantic', 'Indian', 'Arctic'],
    correctAnswerIndex: 1,
    points: 20,
    hint: 'It is off the southeastern coast of the US.',
  },
  {
    category: 'Geography',
    question: 'Which two countries share the longest international border?',
    options: [
      'USA and Mexico',
      'Russia and China',
      'USA and Canada',
      'India and Pakistan',
    ],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'It is often referred to as the International Boundary.',
  },
  {
    category: 'Geography',
    question: 'What is the smallest ocean in the world?',
    options: [
      'Indian Ocean',
      'Southern Ocean',
      'Atlantic Ocean',
      'Arctic Ocean',
    ],
    correctAnswerIndex: 3,
    points: 20,
    hint: 'It surrounds the North Pole.',
  },
  {
    category: 'Geography',
    question: 'Which African country has the highest population?',
    options: ['Egypt', 'South Africa', 'Nigeria', 'Ethiopia'],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'Its capital is Abuja.',
  },
  {
    category: 'Geography',
    question: 'The Grand Canyon is located in which U.S. state?',
    options: ['Nevada', 'Arizona', 'Utah', 'Colorado'],
    correctAnswerIndex: 1,
    points: 10,
    hint: "The state's capital is Phoenix.",
  },
  {
    category: 'Geography',
    question: 'Which country is shaped like a boot?',
    options: ['Greece', 'Portugal', 'Italy', 'Spain'],
    correctAnswerIndex: 2,
    points: 10,
    hint: "It's famous for pizza and pasta.",
  },
  {
    category: 'Geography',
    question: 'What is the capital of New Zealand?',
    options: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton'],
    correctAnswerIndex: 1,
    points: 20,
    hint: 'It is located at the south-western tip of the North Island.',
  },

  // =========================================================================
  // Science
  // =========================================================================
  {
    category: 'Science',
    question: "What is the atom's smallest unit?",
    options: ['Proton', 'Neutron', 'Electron', 'Quark'],
    correctAnswerIndex: 2,
    points: 30,
    hint: 'It is negatively charged and orbits the nucleus.',
  },
  {
    category: 'Science',
    question:
      'What is the process by which plants use sunlight to produce food?',
    options: [
      'Photosynthesis',
      'Cellular respiration',
      'Fermentation',
      'Chemosynthesis',
    ],
    correctAnswerIndex: 0,
    points: 30,
    hint: 'This process produces glucose and oxygen.',
  },
  {
    category: 'Science',
    question:
      'What is the theory that explains the origin and evolution of the universe?',
    options: [
      'Big Bang theory',
      'Steady-state theory',
      'Geocentric theory',
      'Heliocentric theory',
    ],
    correctAnswerIndex: 0,
    points: 30,
    hint: 'This theory suggests the universe began as a singularity.',
  },
  {
    category: 'Science',
    question: 'What is the chemical symbol for gold?',
    options: ['Ag', 'Au', 'Pb', 'Pt'],
    correctAnswerIndex: 1,
    points: 10,
    hint: "Its symbol comes from the Latin word 'Aurum.'",
  },
  {
    category: 'Science',
    question: 'What planet is known as the Red Planet?',
    options: ['Earth', 'Venus', 'Mars', 'Jupiter'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'It has the largest volcano in the solar system.',
  },
  {
    category: 'Science',
    question: 'What gas do plants absorb from the atmosphere?',
    options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'It is a greenhouse gas.',
  },
  {
    category: 'Science',
    question: 'What is the hardest natural substance on Earth?',
    options: ['Gold', 'Iron', 'Diamond', 'Platinum'],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'It is commonly used in jewelry and cutting tools.',
  },
  {
    category: 'Science',
    question: 'What planet is closest to the Sun?',
    options: ['Venus', 'Earth', 'Mercury', 'Mars'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'It has the shortest orbital period.',
  },
  {
    category: 'Science',
    question: "What is the most abundant gas in the Earth's atmosphere?",
    options: ['Oxygen', 'Hydrogen', 'Carbon Dioxide', 'Nitrogen'],
    correctAnswerIndex: 3,
    points: 10,
    hint: "It makes up about 78% of the Earth's atmosphere.",
  },
  {
    category: 'Science',
    question: 'What part of the cell contains the genetic material?',
    options: ['Cytoplasm', 'Ribosome', 'Nucleus', 'Mitochondria'],
    correctAnswerIndex: 2,
    points: 20,
    hint: "It is often referred to as the 'control center' of the cell.",
  },
  {
    category: 'Science',
    question: 'What is the chemical symbol for water?',
    options: ['CO2', 'H2O', 'O2', 'NaCl'],
    correctAnswerIndex: 1,
    points: 10,
    hint: 'It consists of two hydrogen atoms and one oxygen atom.',
  },
  {
    category: 'Science',
    question: "Which planet is known as the Earth's 'twin' due to its size?",
    options: ['Mars', 'Venus', 'Neptune', 'Uranus'],
    correctAnswerIndex: 1,
    points: 20,
    hint: 'It is the hottest planet in our solar system.',
  },
  {
    category: 'Science',
    question: 'What force keeps the planets in orbit around the Sun?',
    options: ['Magnetism', 'Friction', 'Gravity', 'Inertia'],
    correctAnswerIndex: 2,
    points: 10,
    hint: "It's the same force that pulls an apple to the ground.",
  },
  {
    category: 'Science',
    question: 'Who developed the theory of relativity?',
    options: [
      'Isaac Newton',
      'Galileo Galilei',
      'Nikola Tesla',
      'Albert Einstein',
    ],
    correctAnswerIndex: 3,
    points: 20,
    hint: 'He is famous for the equation E=mc^2.',
  },
  {
    category: 'Science',
    question: 'What is the center of an atom called?',
    options: ['Electron', 'Proton', 'Nucleus', 'Neutrino'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'It contains protons and neutrons.',
  },
  {
    category: 'Science',
    question: 'Which blood type is known as the universal donor?',
    options: ['Type A', 'Type B', 'Type AB', 'Type O'],
    correctAnswerIndex: 3,
    points: 30,
    hint: 'Specifically, the negative variant of this type.',
  },
  {
    category: 'Science',
    question: 'What is the speed of light in a vacuum?',
    options: ['~300,000 km/s', '~150,000 km/s', '~1,000,000 km/s', '~343 m/s'],
    correctAnswerIndex: 0,
    points: 30,
    hint: "It's roughly 186,000 miles per second.",
  },
  {
    category: 'Science',
    question:
      'Which part of the human brain controls balance and coordination?',
    options: ['Cerebrum', 'Cerebellum', 'Brainstem', 'Hypothalamus'],
    correctAnswerIndex: 1,
    points: 30,
    hint: "Its name is Latin for 'little brain'.",
  },
  {
    category: 'Science',
    question: 'What is the primary function of white blood cells?',
    options: ['Carry oxygen', 'Clot blood', 'Fight infection', 'Digest food'],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'They are part of the immune system.',
  },
  {
    category: 'Science',
    question: "What element makes up the majority of the Sun's mass?",
    options: ['Oxygen', 'Carbon', 'Helium', 'Hydrogen'],
    correctAnswerIndex: 3,
    points: 20,
    hint: 'It is the lightest element on the periodic table.',
  },
  {
    category: 'Science',
    question: 'How many bones are in the adult human body?',
    options: ['201', '206', '210', '215'],
    correctAnswerIndex: 1,
    points: 20,
    hint: 'Babies are born with more, but they fuse together over time.',
  },
  {
    category: 'Science',
    question: 'What type of animal is a frog?',
    options: ['Reptile', 'Amphibian', 'Mammal', 'Fish'],
    correctAnswerIndex: 1,
    points: 10,
    hint: 'They usually start their lives in the water and then move to land.',
  },
  {
    category: 'Science',
    question: 'What is the chemical symbol for sodium?',
    options: ['So', 'Sd', 'Na', 'Nd'],
    correctAnswerIndex: 2,
    points: 20,
    hint: "It comes from the Latin word 'Natrium'.",
  },
  {
    category: 'Science',
    question: 'Which organ in the human body produces insulin?',
    options: ['Liver', 'Pancreas', 'Kidney', 'Stomach'],
    correctAnswerIndex: 1,
    points: 20,
    hint: 'It sits behind the stomach.',
  },
  {
    category: 'Science',
    question: 'What is the rarest blood type among humans?',
    options: ['O-', 'A+', 'AB-', 'B-'],
    correctAnswerIndex: 2,
    points: 30,
    hint: 'It is a combination of two antigens and lacks the Rh factor.',
  },
  {
    category: 'Science',
    question: 'What gas gives the planet Neptune its blue color?',
    options: ['Ammonia', 'Methane', 'Hydrogen', 'Helium'],
    correctAnswerIndex: 1,
    points: 30,
    hint: 'It absorbs red light.',
  },
  {
    category: 'Science',
    question: 'Who is credited with inventing the first practical telephone?',
    options: [
      'Thomas Edison',
      'Alexander Graham Bell',
      'Nikola Tesla',
      'Guglielmo Marconi',
    ],
    correctAnswerIndex: 1,
    points: 10,
    hint: 'His first transmitted words were to his assistant, Mr. Watson.',
  },
  {
    category: 'Science',
    question: 'At what temperature does water boil in Celsius?',
    options: ['0', '50', '100', '212'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'It is equivalent to 212 Fahrenheit.',
  },
  {
    category: 'Science',
    question: 'What kind of energy is stored in a stretched rubber band?',
    options: ['Kinetic', 'Thermal', 'Chemical', 'Potential'],
    correctAnswerIndex: 3,
    points: 20,
    hint: "It's the energy of position or state.",
  },
  {
    category: 'Science',
    question: 'What is the closest star to Earth?',
    options: ['Alpha Centauri', 'Sirius', 'Proxima Centauri', 'The Sun'],
    correctAnswerIndex: 3,
    points: 10,
    hint: 'We see it every day.',
  },

  // =========================================================================
  // Literature
  // =========================================================================
  {
    category: 'Literature',
    question: "Who wrote the novel 'Pride and Prejudice'?",
    options: [
      'Jane Austen',
      'William Shakespeare',
      'Charles Dickens',
      'Charlotte Brontë',
    ],
    correctAnswerIndex: 0,
    points: 10,
    hint: 'This novel features characters like Elizabeth Bennet and Mr. Darcy.',
  },
  {
    category: 'Literature',
    question:
      "What is the epic poem that tells the story of Odysseus' journey home after the Trojan War?",
    options: ['The Iliad', 'The Odyssey', 'The Aeneid', 'The Metamorphoses'],
    correctAnswerIndex: 1,
    points: 20,
    hint: 'This poem is attributed to Homer.',
  },
  {
    category: 'Literature',
    question: "Who is the main character in Shakespeare's play 'Hamlet'?",
    options: ['Hamlet', 'Romeo', 'Julius Caesar', 'King Lear'],
    correctAnswerIndex: 0,
    points: 30,
    hint: 'He is the Prince of Denmark.',
  },
  {
    category: 'Literature',
    question: "Who wrote 'To Kill a Mockingbird'?",
    options: [
      'Harper Lee',
      'Mark Twain',
      'F. Scott Fitzgerald',
      'Ernest Hemingway',
    ],
    correctAnswerIndex: 0,
    points: 20,
    hint: 'The author won a Pulitzer Prize for this novel.',
  },
  {
    category: 'Literature',
    question: 'What is the title of the first Harry Potter book?',
    options: [
      'Harry Potter and the Chamber of Secrets',
      'Harry Potter and the Goblet of Fire',
      "Harry Potter and the Philosopher's Stone",
      'Harry Potter and the Order of the Phoenix',
    ],
    correctAnswerIndex: 2,
    points: 10,
    hint: "In some countries, it is titled 'Harry Potter and the Sorcerer's Stone.'",
  },
  {
    category: 'Literature',
    question: "Who wrote '1984'?",
    options: ['George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'H.G. Wells'],
    correctAnswerIndex: 0,
    points: 20,
    hint: 'This novel is a dystopian depiction of a totalitarian regime.',
  },
  {
    category: 'Literature',
    question: "In 'Moby Dick', what is the name of the ship?",
    options: ['Pequod', 'Beagle', 'Nautilus', 'Hispaniola'],
    correctAnswerIndex: 0,
    points: 30,
    hint: 'It is the ship commanded by Captain Ahab.',
  },
  {
    category: 'Literature',
    question: "Who is the author of 'The Great Gatsby'?",
    options: [
      'Ernest Hemingway',
      'F. Scott Fitzgerald',
      'William Faulkner',
      'John Steinbeck',
    ],
    correctAnswerIndex: 1,
    points: 10,
    hint: 'This novel is set during the Roaring Twenties.',
  },
  {
    category: 'Literature',
    question: "What is the setting of Shakespeare's 'Romeo and Juliet'?",
    options: ['Rome', 'Paris', 'Verona', 'London'],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'This Italian city is the home of the Capulet and Montague families.',
  },
  {
    category: 'Literature',
    question: "Who wrote 'The Catcher in the Rye'?",
    options: ['J.D. Salinger', 'Harper Lee', 'Mark Twain', 'Ernest Hemingway'],
    correctAnswerIndex: 0,
    points: 20,
    hint: 'The protagonist of this novel is Holden Caulfield.',
  },
  {
    category: 'Literature',
    question: "Who wrote 'Frankenstein'?",
    options: [
      'Mary Shelley',
      'Bram Stoker',
      'Edgar Allan Poe',
      'H.P. Lovecraft',
    ],
    correctAnswerIndex: 0,
    points: 20,
    hint: 'She wrote it as part of a ghost story competition among friends.',
  },
  {
    category: 'Literature',
    question: "Which novel features the character 'Holden Caulfield'?",
    options: [
      'The Great Gatsby',
      'The Catcher in the Rye',
      'Of Mice and Men',
      'Lord of the Flies',
    ],
    correctAnswerIndex: 1,
    points: 10,
    hint: "It's a famous novel about teenage angst.",
  },
  {
    category: 'Literature',
    question: "Who is the author of the 'A Song of Ice and Fire' series?",
    options: [
      'J.R.R. Tolkien',
      'C.S. Lewis',
      'George R.R. Martin',
      'Brandon Sanderson',
    ],
    correctAnswerIndex: 2,
    points: 10,
    hint: "The series was adapted into 'Game of Thrones'.",
  },
  {
    category: 'Literature',
    question: "In 'The Hobbit', what is the name of the dragon?",
    options: ['Glaurung', 'Smaug', 'Balerion', 'Norbert'],
    correctAnswerIndex: 1,
    points: 20,
    hint: 'He guards the treasure in the Lonely Mountain.',
  },
  {
    category: 'Literature',
    question: "Who wrote 'The Odyssey'?",
    options: ['Virgil', 'Homer', 'Sophocles', 'Euripides'],
    correctAnswerIndex: 1,
    points: 10,
    hint: "He is also credited with writing 'The Iliad'.",
  },
  {
    category: 'Literature',
    question: 'What pen name did Samuel Langhorne Clemens use?',
    options: ['Lewis Carroll', 'Mark Twain', 'Dr. Seuss', 'George Orwell'],
    correctAnswerIndex: 1,
    points: 20,
    hint: 'He wrote about Tom Sawyer and Huckleberry Finn.',
  },
  {
    category: 'Literature',
    question: 'Which of these is a play by Arthur Miller?',
    options: [
      'A Streetcar Named Desire',
      'Death of a Salesman',
      'The Glass Menagerie',
      "Who's Afraid of Virginia Woolf?",
    ],
    correctAnswerIndex: 1,
    points: 30,
    hint: 'The main character is named Willy Loman.',
  },
  {
    category: 'Literature',
    question: "In which city is 'Les Misérables' primarily set?",
    options: ['London', 'Rome', 'Paris', 'Berlin'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'It takes place in France.',
  },
  {
    category: 'Literature',
    question: "Who wrote 'Jane Eyre'?",
    options: [
      'Jane Austen',
      'Emily Brontë',
      'Charlotte Brontë',
      'Mary Ann Evans',
    ],
    correctAnswerIndex: 2,
    points: 30,
    hint: "Her sister wrote 'Wuthering Heights'.",
  },
  {
    category: 'Literature',
    question:
      'What is the name of the wizard prison in the Harry Potter series?',
    options: ['Azkaban', 'Nurmengard', 'Tartarus', 'Baskerville'],
    correctAnswerIndex: 0,
    points: 10,
    hint: 'It is guarded by Dementors.',
  },
  {
    category: 'Literature',
    question: "Which book begins with 'Call me Ishmael'?",
    options: [
      'Treasure Island',
      'Moby Dick',
      'The Old Man and the Sea',
      'Heart of Darkness',
    ],
    correctAnswerIndex: 1,
    points: 20,
    hint: "It's about a captain obsessively hunting a white whale.",
  },
  {
    category: 'Literature',
    question: "Who wrote the play 'Macbeth'?",
    options: [
      'Christopher Marlowe',
      'Ben Jonson',
      'William Shakespeare',
      'John Webster',
    ],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'He is often called the Bard of Avon.',
  },
  {
    category: 'Literature',
    question: "What dystopian novel features a 'Big Brother'?",
    options: [
      'Brave New World',
      'Fahrenheit 451',
      '1984',
      "The Handmaid's Tale",
    ],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'It was written by George Orwell.',
  },
  {
    category: 'Literature',
    question: 'Who is the creator of the detective Sherlock Holmes?',
    options: [
      'Agatha Christie',
      'Arthur Conan Doyle',
      'Edgar Allan Poe',
      'G.K. Chesterton',
    ],
    correctAnswerIndex: 1,
    points: 10,
    hint: 'He was a British writer and medical doctor.',
  },
  {
    category: 'Literature',
    question: "What is the name of the pig leader in 'Animal Farm'?",
    options: ['Snowball', 'Old Major', 'Squealer', 'Napoleon'],
    correctAnswerIndex: 3,
    points: 30,
    hint: 'He shares his name with a famous French emperor.',
  },
  {
    category: 'Literature',
    question: "Who wrote 'The Chronicles of Narnia'?",
    options: ['J.R.R. Tolkien', 'Roald Dahl', 'C.S. Lewis', 'J.K. Rowling'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'He was close friends with J.R.R. Tolkien.',
  },
  {
    category: 'Literature',
    question: "In 'The Hunger Games', what district is Katniss Everdeen from?",
    options: ['District 1', 'District 9', 'District 11', 'District 12'],
    correctAnswerIndex: 3,
    points: 20,
    hint: 'It is the poorest district, known for coal mining.',
  },
  {
    category: 'Literature',
    question: "Who wrote the epic poem 'The Divine Comedy'?",
    options: ['Homer', 'Virgil', 'Dante Alighieri', 'Ovid'],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'It features a journey through Hell, Purgatory, and Paradise.',
  },
  {
    category: 'Literature',
    question: 'What is the real name of the author Dr. Seuss?',
    options: [
      'Theodor Seuss Geisel',
      'Charles Lutwidge Dodgson',
      'E.B. White',
      'Shel Silverstein',
    ],
    correctAnswerIndex: 0,
    points: 30,
    hint: 'His first name is Theodor.',
  },
  {
    category: 'Literature',
    question: 'Which classic novel features the March sisters?',
    options: [
      'Little Women',
      'Sense and Sensibility',
      'Emma',
      'Anne of Green Gables',
    ],
    correctAnswerIndex: 0,
    points: 20,
    hint: 'The author is Louisa May Alcott.',
  },

  // =========================================================================
  // Math
  // =========================================================================
  {
    category: 'Math',
    question: 'What is the square root of 25?',
    options: ['2', '5', '10', 'There is no real number solution'],
    correctAnswerIndex: 1,
    points: 10,
    hint: 'The answer is a prime number.',
  },
  {
    category: 'Math',
    question: 'What is the formula for the area of a circle?',
    options: ['πr', '2πr', 'πr²', '4πr²'],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'It involves the square of the radius.',
  },
  {
    category: 'Math',
    question: 'What is the Pythagorean theorem?',
    options: [
      'a² + b² = c²',
      'a + b = c',
      'a * b = c',
      'There is no such theorem',
    ],
    correctAnswerIndex: 0,
    points: 30,
    hint: 'It applies to right-angled triangles.',
  },
  {
    category: 'Math',
    question: 'What is 7 times 8?',
    options: ['54', '56', '58', '60'],
    correctAnswerIndex: 1,
    points: 10,
    hint: "It's a multiplication fact often memorized in school.",
  },
  {
    category: 'Math',
    question: 'What is the derivative of x²?',
    options: ['x', '2x', 'x²', '2'],
    correctAnswerIndex: 1,
    points: 30,
    hint: 'It involves the power rule.',
  },
  {
    category: 'Math',
    question: 'What is the value of π (pi) approximately?',
    options: ['2.14', '3.14', '4.14', '5.14'],
    correctAnswerIndex: 1,
    points: 10,
    hint: 'It is commonly rounded to two decimal places.',
  },
  {
    category: 'Math',
    question: 'What is 12 squared?',
    options: ['120', '122', '144', '148'],
    correctAnswerIndex: 2,
    points: 20,
    hint: "It's 12 times 12.",
  },
  {
    category: 'Math',
    question: 'What is the slope of the line y = 3x + 2?',
    options: ['2', '3', '3/2', '1/3'],
    correctAnswerIndex: 1,
    points: 20,
    hint: 'The coefficient of x represents the slope.',
  },
  {
    category: 'Math',
    question: 'What is the result of 2^3?',
    options: ['4', '6', '8', '10'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'It is 2 multiplied by itself three times.',
  },
  {
    category: 'Math',
    question: 'What is the integral of 2x?',
    options: ['x', 'x^2', 'x^2 + C', '2x + C'],
    correctAnswerIndex: 2,
    points: 30,
    hint: 'It involves adding a constant of integration.',
  },
  {
    category: 'Math',
    question: 'What is 15% of 200?',
    options: ['15', '20', '30', '45'],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'Calculate 10% first, then add half of that amount.',
  },
  {
    category: 'Math',
    question: 'What is the next prime number after 7?',
    options: ['8', '9', '11', '13'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'A prime number is only divisible by 1 and itself.',
  },
  {
    category: 'Math',
    question: 'What is the interior angle sum of a triangle?',
    options: ['90 degrees', '180 degrees', '360 degrees', '720 degrees'],
    correctAnswerIndex: 1,
    points: 10,
    hint: 'It is exactly half of the angle sum of a rectangle.',
  },
  {
    category: 'Math',
    question: 'If x = 4, what is the value of 3x - 5?',
    options: ['7', '9', '12', '17'],
    correctAnswerIndex: 0,
    points: 10,
    hint: 'Multiply 3 by 4 first.',
  },
  {
    category: 'Math',
    question: 'What is 5 cubed?',
    options: ['15', '25', '125', '625'],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'It is 5 * 5 * 5.',
  },
  {
    category: 'Math',
    question:
      'What do we call an angle that is greater than 90 degrees but less than 180 degrees?',
    options: ['Acute angle', 'Right angle', 'Obtuse angle', 'Reflex angle'],
    correctAnswerIndex: 2,
    points: 20,
    hint: "It sounds like a word meaning 'slow to understand'.",
  },
  {
    category: 'Math',
    question: 'What is the square root of 144?',
    options: ['10', '12', '14', '16'],
    correctAnswerIndex: 1,
    points: 10,
    hint: "It's equivalent to a dozen.",
  },
  {
    category: 'Math',
    question: 'How many sides does a hexagon have?',
    options: ['5', '6', '7', '8'],
    correctAnswerIndex: 1,
    points: 10,
    hint: "Think of the letter 'x' in the prefix.",
  },
  {
    category: 'Math',
    question: 'What is the value of 0 factorial (0!)?',
    options: ['0', '1', '-1', 'undefined'],
    correctAnswerIndex: 1,
    points: 30,
    hint: 'By mathematical convention, it is not zero.',
  },
  {
    category: 'Math',
    question: 'If a circle has a diameter of 10, what is its radius?',
    options: ['5', '10', '15', '20'],
    correctAnswerIndex: 0,
    points: 10,
    hint: 'The radius is half the diameter.',
  },
  {
    category: 'Math',
    question: 'What is the probability of flipping a coin and getting heads?',
    options: ['1/4', '1/3', '1/2', '1'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'There are only two possible outcomes.',
  },
  {
    category: 'Math',
    question: 'What is 100 divided by 0?',
    options: ['0', '100', '1', 'Undefined'],
    correctAnswerIndex: 3,
    points: 20,
    hint: 'You cannot split something into zero parts.',
  },
  {
    category: 'Math',
    question: 'Which of these is not a prime number?',
    options: ['2', '3', '4', '5'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'It is divisible by 2.',
  },
  {
    category: 'Math',
    question: 'What is 3/4 converted to a decimal?',
    options: ['0.34', '0.75', '3.4', '0.25'],
    correctAnswerIndex: 1,
    points: 10,
    hint: 'Think of three quarters in a dollar.',
  },
  {
    category: 'Math',
    question: 'Solve for y: 2y + 4 = 12',
    options: ['2', '4', '6', '8'],
    correctAnswerIndex: 1,
    points: 20,
    hint: 'Subtract 4, then divide by 2.',
  },
  {
    category: 'Math',
    question: 'What is the top number of a fraction called?',
    options: ['Numerator', 'Denominator', 'Quotient', 'Divisor'],
    correctAnswerIndex: 0,
    points: 20,
    hint: 'The bottom is called the denominator.',
  },
  {
    category: 'Math',
    question: 'What is the perimeter of a rectangle with sides 5 and 10?',
    options: ['15', '30', '50', '100'],
    correctAnswerIndex: 1,
    points: 20,
    hint: 'Add all four sides together.',
  },
  {
    category: 'Math',
    question: 'How many centimeters are in a meter?',
    options: ['10', '100', '1000', '10000'],
    correctAnswerIndex: 1,
    points: 10,
    hint: "The prefix 'centi' means one hundredth.",
  },
  {
    category: 'Math',
    question:
      'What is the next number in the Fibonacci sequence: 0, 1, 1, 2, 3, 5, ...?',
    options: ['6', '7', '8', '9'],
    correctAnswerIndex: 2,
    points: 30,
    hint: 'Add the two previous numbers together.',
  },
  {
    category: 'Math',
    question: 'What is 9 multiplied by 9?',
    options: ['72', '81', '90', '99'],
    correctAnswerIndex: 1,
    points: 10,
    hint: "It's one less than 10 times 9.",
  },

  // =========================================================================
  // Technology
  // =========================================================================
  {
    category: 'Technology',
    question: 'Who is widely considered the father of computer science?',
    options: ['Charles Babbage', 'Alan Turing', 'Steve Jobs', 'Bill Gates'],
    correctAnswerIndex: 1,
    points: 30,
    hint: 'He played a crucial role in cracking intercepted coded messages in WWII.',
  },
  {
    category: 'Technology',
    question: 'What does HTTP stand for?',
    options: [
      'Hypertext Transfer Protocol',
      'Hyperlink Transfer Technology',
      'Hypertext Transmission Process',
      'Hyper Transfer Text Protocol',
    ],
    correctAnswerIndex: 0,
    points: 20,
    hint: 'It is the foundation of data communication for the World Wide Web.',
  },
  {
    category: 'Technology',
    question: 'Which company developed the iPhone?',
    options: ['Samsung', 'Google', 'Apple', 'Nokia'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'This company was co-founded by Steve Jobs.',
  },
  {
    category: 'Technology',
    question: 'What does CPU stand for?',
    options: [
      'Computer Personal Unit',
      'Central Processing Unit',
      'Central Process Utility',
      'Computer Processing Unit',
    ],
    correctAnswerIndex: 1,
    points: 10,
    hint: 'It acts as the "brain" of the computer.',
  },
  {
    category: 'Technology',
    question: 'In what year was the World Wide Web invented?',
    options: ['1985', '1989', '1995', '1999'],
    correctAnswerIndex: 1,
    points: 30,
    hint: 'It was invented by Tim Berners-Lee near the end of the 80s.',
  },
  {
    category: 'Technology',
    question: 'What does GUI stand for in computing?',
    options: [
      'General Utility Interface',
      'Graphical User Interface',
      'Graphic Utility Integration',
      'General User Interaction',
    ],
    correctAnswerIndex: 1,
    points: 20,
    hint: 'It allows users to interact with devices through graphical icons.',
  },
  {
    category: 'Technology',
    question:
      'Which popular programming language is named after a British comedy group?',
    options: ['Java', 'Ruby', 'Python', 'C++'],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'Its name makes people think of a large snake.',
  },
  {
    category: 'Technology',
    question: 'Who co-founded Microsoft alongside Paul Allen?',
    options: ['Steve Wozniak', 'Larry Page', 'Mark Zuckerberg', 'Bill Gates'],
    correctAnswerIndex: 3,
    points: 10,
    hint: 'He was once the richest person in the world for many consecutive years.',
  },
  {
    category: 'Technology',
    question:
      'What type of computer memory is volatile and lost when power is turned off?',
    options: ['ROM', 'Hard Drive', 'RAM', 'Flash Drive'],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'It stands for Random Access Memory.',
  },
  {
    category: 'Technology',
    question: 'Which company owns the social media platform TikTok?',
    options: ['Meta', 'Tencent', 'ByteDance', 'Alphabet'],
    correctAnswerIndex: 2,
    points: 30,
    hint: 'It is a Chinese internet technology company headquartered in Beijing.',
  },
  {
    category: 'Technology',
    question: "What does 'HTML' stand for?",
    options: [
      'Hyper Text Markup Language',
      'High Tech Modern Language',
      'Hyperlinks and Text Markup Language',
      'Home Tool Markup Language',
    ],
    correctAnswerIndex: 0,
    points: 20,
    hint: "It's the standard markup language for documents designed to be displayed in a web browser.",
  },
  {
    category: 'Technology',
    question: 'Which tech company uses the name of a fruit as its logo?',
    options: ['Blackberry', 'Apple', 'Raspberry Pi', 'All of the above'],
    correctAnswerIndex: 3,
    points: 20,
    hint: 'Think carefully about all the options.',
  },
  {
    category: 'Technology',
    question: "What does 'URL' stand for?",
    options: [
      'Universal Resource Locator',
      'Uniform Resource Locator',
      'Unified Routing Link',
      'Universal Routing Link',
    ],
    correctAnswerIndex: 1,
    points: 30,
    hint: "It's the mechanism used by browsers to retrieve any published resource on the web.",
  },
  {
    category: 'Technology',
    question: 'Who is the CEO of Tesla as of 2024?',
    options: ['Jeff Bezos', 'Bill Gates', 'Elon Musk', 'Mark Zuckerberg'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'He also founded SpaceX.',
  },
  {
    category: 'Technology',
    question: 'What is the main function of an operating system?',
    options: [
      'To protect against viruses',
      'To manage computer hardware and software resources',
      'To browse the internet',
      'To compile code',
    ],
    correctAnswerIndex: 1,
    points: 20,
    hint: 'Windows and macOS are examples of one.',
  },
  {
    category: 'Technology',
    question: 'Which of these is not an internet browser?',
    options: ['Google Chrome', 'Mozilla Firefox', 'Linux', 'Safari'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'One of these is an open-source operating system kernel.',
  },
  {
    category: 'Technology',
    question: 'What does PDF stand for?',
    options: [
      'Personal Document Format',
      'Portable Document Format',
      'Printed Document File',
      'Public Data Format',
    ],
    correctAnswerIndex: 1,
    points: 20,
    hint: 'It was created by Adobe in 1992.',
  },
  {
    category: 'Technology',
    question: "In computer science, what is a 'bug'?",
    options: [
      'A hardware component',
      'An error or flaw in a program',
      'A type of virus',
      'A small microchip',
    ],
    correctAnswerIndex: 1,
    points: 10,
    hint: 'Grace Hopper famously found a literal moth in a computer.',
  },
  {
    category: 'Technology',
    question: 'Which company bought YouTube in 2006?',
    options: ['Microsoft', 'Yahoo', 'Google', 'Facebook'],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'They own the largest search engine in the world.',
  },
  {
    category: 'Technology',
    question: "What does 'Wi-Fi' officially stand for?",
    options: [
      'Wireless Fidelity',
      'Wireless Firewire',
      'Wired Fiber',
      'Nothing, it is a trademarked phrase',
    ],
    correctAnswerIndex: 3,
    points: 30,
    hint: 'It is a common misconception that it stands for Wireless Fidelity.',
  },
  {
    category: 'Technology',
    question: 'Which of these is a popular version control system?',
    options: ['Git', 'Python', 'Docker', 'Node.js'],
    correctAnswerIndex: 0,
    points: 20,
    hint: 'It was created by Linus Torvalds.',
  },
  {
    category: 'Technology',
    question: "What does 'AI' stand for?",
    options: [
      'Automated Intelligence',
      'Artificial Intelligence',
      'Algorithmic Information',
      'Advanced Integration',
    ],
    correctAnswerIndex: 1,
    points: 10,
    hint: "It's the simulation of human intelligence by machines.",
  },
  {
    category: 'Technology',
    question:
      'What is the name of the first electronic general-purpose computer?',
    options: ['UNIVAC', 'ENIAC', 'EDVAC', 'Altair'],
    correctAnswerIndex: 1,
    points: 30,
    hint: 'It was completed in 1945 and filled an entire room.',
  },
  {
    category: 'Technology',
    question:
      'Which programming language is known for its use in iOS app development?',
    options: ['Java', 'Kotlin', 'Swift', 'C#'],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'It was developed by Apple and released in 2014.',
  },
  {
    category: 'Technology',
    question: 'What does SSD stand for in storage technology?',
    options: [
      'Solid State Drive',
      'Super Speed Disk',
      'Static Storage Drive',
      'Solid System Disk',
    ],
    correctAnswerIndex: 0,
    points: 20,
    hint: 'It uses flash memory rather than spinning magnetic platters.',
  },
  {
    category: 'Technology',
    question: 'What was the first commercially successful video game?',
    options: ['Pac-Man', 'Space Invaders', 'Pong', 'Tetris'],
    correctAnswerIndex: 2,
    points: 30,
    hint: "It's a simple table tennis sports game released by Atari.",
  },
  {
    category: 'Technology',
    question: 'What company created the Android operating system?',
    options: ['Samsung', 'Apple', 'Google', 'Microsoft'],
    correctAnswerIndex: 2,
    points: 10,
    hint: 'They also developed the Chrome browser.',
  },
  {
    category: 'Technology',
    question: "What does 'VPN' stand for?",
    options: [
      'Virtual Private Network',
      'Visual Processing Node',
      'Verified Public Network',
      'Virtual Protected Network',
    ],
    correctAnswerIndex: 0,
    points: 20,
    hint: 'It establishes a secure, encrypted connection over the internet.',
  },
  {
    category: 'Technology',
    question: 'Which of these is a relational database management system?',
    options: ['MongoDB', 'Redis', 'MySQL', 'Cassandra'],
    correctAnswerIndex: 2,
    points: 30,
    hint: 'It uses SQL (Structured Query Language).',
  },
  {
    category: 'Technology',
    question: 'What was the name of the first artificial Earth satellite?',
    options: ['Apollo 11', 'Voyager 1', 'Sputnik 1', 'Explorer 1'],
    correctAnswerIndex: 2,
    points: 20,
    hint: 'It was launched by the Soviet Union in 1957.',
  },
];
